### ISSUE TITLE
Port quasimodo to soma_llsd

### ISSUE THREAD

**Issue by nilsbore** [jayyoung/soma_llsd#1]
I'm gonna start and port quasimodo to this framework to see what works/doesn't, to be continued... =).

**Comment by jayyoung** [comment]
~~may god have mercy on your soul~~ no please just let me know about what ever issues you run into, and I'll fix them. There's still one or two things missing I haven't got around to adding yet, like a service to insert into the scene store and automatically populate all of the topics like the state of /tf, but I'm not sure if the scene store is something you will even need/want to make use of, it's all optional.

**Comment by nilsbore** [comment]
Ok, this is done, we're storing the metarooms in soma_llsd and taking the planned views from soma_llsd.
